---
  api_token:
    description: "api token for whatsapp chat-api.com instance"
    type: "string"
    secret: true
    required: true
  api_instance:
    description: "api instace of whatsapp chat-api.com"
    type: "string"
    secret: true
    required: true
  api_server:
    description: "api instace of whatsapp chat-api.com"
    type: "string"
    secret: true
    required: true
